# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

EAPI="2"

inherit distutils

DESCRIPTION="A platform for distributed translation submissions"
HOMEPAGE="http://transifex.org/"
SRC_URI="http://transifex.org/files/${P}.tar.gz"
LICENSE="GPL-2"
KEYWORDS="~amd64 ~x86"
SLOT="0"
IUSE="mysql sqlite postgres subversion"
DEPEND="dev-python/setuptools
		mysql? ( dev-python/django[mysql] )
		sqlite? ( dev-python/django[sqlite] )
		postgres? ( dev-python/django[postgres] )"
RDEPEND=">=dev-python/django-1.0
	>=dev-python/pygments-0.9
	=dev-python/django-contact-form-9999
	dev-python/django-authopenid
	dev-python/django-evolution
	>=dev-python/django-notification-0.1.2
	>=dev-python/django-pagination-1.0.5
	dev-python/django-tagging
	dev-python/urlgrabber
	subversion? ( dev-python/pysvn )"

