# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

EAPI="2"

inherit distutils mercurial

DESCRIPTION="A platform for distributed translation submissions"
HOMEPAGE="http://transifex.org/"
#SRC_URI="http://transifex.org/files/${P}.tar.gz"
EHG_REPO_URI="http://code.transifex.org/mainline"

LICENSE="GPL-2"
KEYWORDS="~amd64 ~x86"
SLOT="0"
IUSE="subversion"
DEPEND="dev-python/setuptools"
RDEPEND=">=dev-python/django-1.0
	>=dev-python/pygments-0.9
	=dev-python/django-contact-form-9999
	dev-python/django-authopenid
	dev-python/django-evolution
	>=dev-python/django-notification-0.1.2
	>=dev-python/django-pagination-1.0.5
	dev-python/django-tagging
	dev-python/django-profile
	dev-python/sphinx
	sys-devel/gettext
	subversion? ( dev-python/pysvn )"
#	dev-python/urlgrabber

S="${WORKDIR}"/mainline

src_prepare() {
	epatch "${FILESDIR}"/setup.py.patch || die "epatch failed"
}

#src_install() {
#	distutils_python_version
#	local site_pkg="/usr/$(get_libdir)/python${PYVER}/site-packages/transifex/"
#	export PYTHONPATH="${PYTHONPATH}:${D}/${site_pkg}"
#	dodir ${site_pkg}
#	distutils_src_install
#}

pkg_postinst() {
	einfo
}

