# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

EAPI="2"

inherit distutils

DESCRIPTION="A library to manipulate gettext files (po and mo files)."
HOMEPAGE="http://bitbucket.org/izi/polib/src/"
SRC_URI="http://bitbucket.org/izi/polib/downloads/${P}.tar.gz"
LICENSE="MIT"
KEYWORDS="~amd64 ~x86"
SLOT="0"
IUSE=""
