# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# This ebuild generated by g-cpan 0.16.0

EAPI="2"

MODULE_AUTHOR="NEILW"

inherit perl-module

DESCRIPTION="A simple command-line shell framework."

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
