# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils

DESCRIPTION="A Django app that provides generic per-object-permissions for Django's auth app."
HOMEPAGE="http://bitbucket.org/jezdez/django-authority/"
SRC_URI="http://bitbucket.org/jezdez/django-authority/downloads/${P}.tar.gz"
LICENSE="BSD-2"
KEYWORDS="~amd64 ~x86"
SLOT="0"
IUSE=""
