# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

EAPI=3

inherit distutils

DESCRIPTION="A set of utilities for creating robust pagination tools throughout a django application"
HOMEPAGE="http://django-pagination.googlecode.com/"
SRC_URI="http://django-pagination.googlecode.com/files/${P}.tar.gz"
LICENSE="BSD"
KEYWORDS="~amd64 ~x86"
SLOT="0"
IUSE=""
DEPEND=""
RDEPEND=""

src_test() {
	PYTHONPATH=. "${python}" setup.py test || die "tests failed"
}
