# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils

DESCRIPTION="User notification management for the Django web framework"
HOMEPAGE="http://code.google.com/p/django-notification/"
SRC_URI="http://pypi.python.org/packages/source/d/django-notification/${P}.tar.gz"
LICENSE="MIT"
KEYWORDS="~amd64 ~x86"
SLOT="0"
IUSE=""
DEPEND=""
RDEPEND=""
