# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

EAPI=3

inherit distutils

DESCRIPTION="A Django app that provides helpers for serving static files."
HOMEPAGE="http://bitbucket.org/jezdez/django-staticfiles/"
SRC_URI="http://bitbucket.org/jezdez/django-staticfiles/get/0.3.1.tar.bz2 -> ${P}.tar.bz2"
LICENSE="BSD-2"
KEYWORDS="~amd64 ~x86"
SLOT="0"
IUSE=""
DEPEND="dev-python/setuptools"
RDEPEND=""

S="${WORKDIR}/${PN}"
