# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# This ebuild generated by g-cpan 0.16.0

EAPI="2"

MODULE_AUTHOR="CWEST"
inherit perl-module

DESCRIPTION="SSL support for Net::IMAP::Simple"
LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

DEPEND="dev-perl/IO-Socket-SSL
	dev-perl/Net-IMAP-Simple"
RDEPEND="${DEPEND}"
