# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

EAPI=3
inherit distutils

DESCRIPTION="Django module displaying tabular paginated and sortable data is very easy."
HOMEPAGE="http://github.com/directeur/django-sorting/tree/master"
SRC_URI="mirror://pypi/d/${PN}/${P}.tar.gz"
LICENSE="BSD"
KEYWORDS="~amd64 ~x86"
SLOT="0"
IUSE=""
DEPEND="dev-python/setuptools"
RDEPEND=""
