# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

EAPI="2"
inherit distutils

DESCRIPTION="Django module displaying tabular paginated and sortable data is very easy."
HOMEPAGE="http://github.com/directeur/django-sorting/tree/master"
SRC_URI="http://pypi.python.org/packages/source/d/django-sorting/${P}.tar.gz"
LICENSE="BSD"
KEYWORDS="~amd64 ~x86"
SLOT="0"
IUSE=""
DEPEND="dev-python/setuptools"
