# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

EAPI=3

inherit distutils eutils

DESCRIPTION="A simple yet flexible threaded commenting system."
HOMEPAGE="http://code.google.com/p/django-threadedcomments/"
# there no 0.9 tarball exist
SRC_URI="http://trac.transifex.org/files/deps/${P}.tar.gz"
LICENSE="BSD-2"
KEYWORDS="~amd64 ~x86"
SLOT="0"
IUSE=""
DEPEND="dev-python/setuptools"
RDEPEND=""

src_prepare() {
	# Fix for index creation error
	epatch "${FILESDIR}"/${P}-index-db-fix.patch
}
