# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

EAPI="2"
inherit distutils

DESCRIPTION="Django-filter is a reusable Django application for allowing users to filter queryset dynamically."
HOMEPAGE="http://github.com/alex/django-filter/tree/master"
SRC_URI="http://pypi.python.org/packages/source/d/django-filter/${P}.tar.gz"
LICENSE="BSD-2"
KEYWORDS="~amd64 ~x86"
SLOT="0"
IUSE=""
DEPEND="dev-python/setuptools"
