# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

EAPI="2"
inherit distutils

DESCRIPTION="jQuery-powered auto-complete fields for ForeignKey and ManyToMany fields"
HOMEPAGE="http://code.google.com/p/django-ajax-selects/"
SRC_URI="https://projects.gentoo.ru/attachements/37/ajax-selects-${PV}.tar.bz2"

LICENSE="MIT"
KEYWORDS="~amd64 ~x86"
SLOT="0"
IUSE=""
DEPEND="dev-python/setuptools"
RDEPEND=""

S="${WORKDIR}/Ajax Select-1.0"

pkg_postinst() {
	echo
	einfo "This package may require more dependencies, but portage can't handle with them."
	einfo "Please refer ${HOMEPAGE}"
	echo
}
