# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

EAPI="2"
inherit distutils subversion

DESCRIPTION="jQuery-powered auto-complete fields for ForeignKey and ManyToMany fields"
HOMEPAGE="http://code.google.com/p/django-ajax-selects/"
ESVN_REPO_URI="http://django-ajax-selects.googlecode.com/svn/trunk/"
#SRC_URI="http://django-ajax-selects.googlecode.com/files/${P}.zip"

LICENSE="MIT"
KEYWORDS="~amd64 ~x86"
SLOT="0"
IUSE=""
DEPEND=""
RDEPEND=">=dev-python/django-1.0.2"

#S="${WORKDIR}"/${P}

src_prepare() {
	# build.py misplaced, moving in right directory
	mv "${S}"/ajax_select/setup.py "${S}" || die "move failed"
}

src_install() {
	distutils_src_install
	dodoc ajax_select/docs.txt
}

pkg_postinst() {
	echo
	einfo "This package may require more dependencies, but portage can't handle with them."
	einfo "Please refer /usr/share/doc/${P}/docs.txt"
	echo
}

