# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# This ebuild generated by g-cpan 0.16.9

EAPI=6

DIST_AUTHOR="DCONWAY"
DIST_VERSION="1.048"

inherit perl-module

DESCRIPTION="Add grammatical parsing features to Perl 5.10 regexes"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

DEPEND=">=dev-perl/B-Hooks-Parser-0.190.0
	dev-perl/Module-Build
	dev-lang/perl"
